[project]
name = "ipo-monitor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.13.4",
    "flake8>=7.3.0",
    "pylint>=3.3.7",
    "pyyaml>=6.0.2",
    "requests>=2.32.4",
]
